name: Build and Release Electron App

on:
  push:
    tags:
      - "v*.*.*" # Trigger the workflow for version tags like v1.0.0, v1.1.0, etc.
  workflow_dispatch: # Allow manual triggering from GitHub UI

jobs:
  release:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build app for Mac and Windows
        run: npm run dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.dmg
            dist/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
