name: Build and Release Electron App

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  release:
    runs-on: macos-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with: { node-version: "20" }

      - run: npm install

      - run: npm run dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }} # e.g. "v1.0.3"
          release_name: Release ${{ github.ref_name }}
          draft: false # publish immediately
          prerelease: false
          files: |
            dist/*.dmg
            dist/*.exe
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
